### ISSUE TITLE
User Access/Groups dialog should not rely on message passing to work

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#144]
# Issue

To integrate the `SecurityModelComponent` as a dialog (for controlling user access/group permissions for a model, say), requires the following steps:

1. The parent component must use the `MessagesService.FolderSendMessage()` to pass and store the catalogue item model temporarily
2. Open the `SecurityModelComponent` as a `MatDialog`, which in turn renders the `<mdm-share-with>` and `<mdm-group-access-new>` components
3. Both these security components call `MessagesService.getFolderPermissions()` to fetch the catalogue item model that was previously kept hold of
4. All changes made in the dialog are sent through the `MessagesService.dataChanged()` to notify the parent components.

These steps are unwieldy and unnecessary, going against the standard Angular practices of using input/output binding to pass data between parent and child components.

# Suggestion

This process should be refactored as follows:

1. The `SecurityModelComponent` should accept typed dialog configuration to accept a catalogue item of type `CatalogueItem & SecurableModel` - these provide all the properties required to check read access for a catalogue item.
2. The `<mdm-security-model>` component should then pass the catalogue item down to the `<mdm-share-with>` and `<mdm-group-access-new>` components via new `@Input()` bindings
3. They should also have `@Output` bindings added to respond to changes made
4. The security components now no longer depend `MessagesService`

If, after the dialog is closed, components not related to the parent/child component hierarchy need to be alerted to changes, these should be done via the `BroadcastService` by the calling component, not the dialog anymore. However, the above steps should cater to nearly all scenarios.

# Tasks

- [x] Create type definitions for the `SecurityModelComponent` to accept dialog configuration and results.
- [x] Add `@Input()` and `@Output` bindings to `<mdm-share-with>` and `<mdm-group-access-new>`
- [x] Refactor `<mdm-share-with>` and `<mdm-group-access-new>` to use the new data bindings instead of `MessagesService`
- [x] Update all call sites for opening the dialog correctly.
