### ISSUE TITLE
Improve setup of page route that are allowed for anonymous users

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#264]
Raised because of #258 

# Issue

When adding a new route for a page, it is possible that the route may be allowed for anonymous users. For example, the home page is accessible whether you are signed in or not.

The UIRouter has a transition hook setup in [app-routing.module.ts](https://github.com/MauroDataMapper/mdm-ui/blob/2ec6df00befb0472bf2073651eabf6f3c30b299e/src/app/app-routing.module.ts#L369). This delegates to the `StateRoleAccessService` to check if anonymous access is allowed, by searching a hardcoded list of state names.

If adding a new route and updating this hardcoded list is forgotten, then accessing the page is not possible when not signed in, causing further bugs to be reported.

# Solution

All UIRouter state declarations include an optional `data` property where any related data can be placed. Instead of having a separate hardcoded list to maintain, each state should contain information stating whether it is allowed for public access or not, improving codebase maintenance. Like so:

```ts
export const pageRoutes: { states: Ng2StateDeclaration[] } = {
  states: [
    {
      name: 'appContainer',
      component: AppComponent,
      data: {
        allowAnonymous: true
      }
    },
    {
      name: 'appContainer.mainApp',
      component: AppContainerComponent,
      data: {
        allowAnonymous: true
      }
    },

    {
      name: 'appContainer.mainApp.about',
      url: '/about',
      component: AboutComponent,
      data: {
        allowAnonymous: true
      }
    },
}
```

Then the `StateRoleAccessService` can simply check if `data.allowAnonymous` is `true`.

# Tasks

- [x] Add `data.allowAnonymous` booleans to all states that allow anonymous access. See `StateRoleAccessService` for the current list.
- [x] Update the `roleTransitionHooks` to use this new property to check,
- [x] Remove the hardcoded state name list from `StateRoleAccessService`
- [x] Consider removing `StateRoleAccessService` - code is only required for this transition check, and could be moved elsewhere.
