### ISSUE TITLE
Updates to diagrams in UI

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#633]
The diagramming functionality wasn't a priority during the original Angular migration, but there are now some features that we would like adding or re-instating - some easy and some harder.  This epic ticket is to group and track them.

- [ ] Update the UML class diagram on the Data Model page to include imported data elements and data classes, and class extensions
- [ ] Update the UML diagrams to allow users to click on an attribute or class to go to the details
- [ ] Add a new UML diagrams to Data Class pages, to show the immediate neighbours of that class - contained classes; data elements; reference data elements; imported data elements and data classes; extended data classes;
- [ ] Improve the UML diagrams for a whole dataset to better cope with large models - many classes; many attributes, etc.  They seem to be slow to render - if this is the case and there are improvements to be made, making those.
- [ ] Update the Data Flow diagrams to allow dragging / dropping to create new data flows (along with editing their associated text)

The diagrams are currently created using JointJS.  Part of this work might include a check to make sure there aren't any better libraries we could be using.
