### ISSUE TITLE
Style Tweaks

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper/mdm-ui#679]
Based on the work in the #feature/style-tweaks branch, this epic lists the updates that need to be replayed as a set of coherent, tested updates.  Roughly in the order below, so that the styling remains roughly consistent and usable.  Items will be added to the list as we go through

- [ ] Sticky Footer
- [ ] Restyle Footer
- [ ] Restyle Header
- [ ] Sliding two-column view
- [ ] Restyle Tree
- [ ] Restyle front page
- [ ] Restyle buttons
- [ ] Restyle tooltips
- [ ] Restyle Menus and drop-downs
