### ISSUE TITLE
Ensure that renaming an item also updates any affected links to that item

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-ui#851]
# Description

When an item is modified to have a new name, that item may be referenced through various links back to it. Examples are:

- Semantic links joining items together
- Reference types
- Hyperlinks references as paths contained in the "Description" fields of items

All of these links should be maintained/adjusted so that, if a source item is renamed, then all links back to that item remain correct and do not break.

# Notes

Semantic links and reference types will be easy to support this - they are linked by ID, so renamed labels will naturally flow through the links.

The hyperlinks in the "Description" fields though will be much more difficult. These are URLs which contain Mauro item paths to the items, meaning the label names are used. If one item label were renamed, then every description field in Mauro would have to be checked to see if the old name was referenced, then be updated to the new name. Since there are no structured links between items when hyperlinks are used, this could be a very expensive operation. Some thought/design will be required to enable this.

# Related Issues

This issue will act as the parent issue to trace individual tasks to complete this feature - this issue can act as the final confirmation and testing of the use case.

- [ ] MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#14
- [ ] MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#15
- [ ] MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#17
- [ ] MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#18
